### ISSUE TITLE
Rework: enhance role to support all mariadb versions

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-mariadb#4]
### Type of Report

enhancement

### Actual behaviour

only mariadb repo is possible

### Expected behaviour

create mariadb server regardless version or repository.
Please also have a look at the ideas here: #1

**Comment by daniel-schier** [comment]
maybe you can have a look at ansible-role-sshd.
There i have done this conditional variable including.

**Comment by donvipre** [comment]
I don't see it in there.
Anyway..I think I've found a way to do this.
Will have a deeper look this week.
